# Generated by Django 2.2.7 on 2019-11-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('is_Lucky', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('personname', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('hours', models.IntegerField()),
            ],
        ),
    ]
